# The RAG Knowledge Pipeline — ingesting `sample_pdfs/`, measured end to end

This notebook ingests the 6 real PDFs in `sample_pdfs/` through the **actual**
ingestion pipeline — not a notebook reimplementation of it. Every step below calls
straight into the `app` package the production worker (`python -m app.ingest.worker`) runs:
`app.ingest.pipeline.runner.run_job`, `app.ingest.pipeline.loaders`, `app.ingest.pipeline.chunker`,
`app.ingest.pipeline.metadata_extract`, `app.retrieval.rag.access`, `app.shared.container.build_container`.

Two deliberate deviations from `.env` for **this run only** (set in code, not by
editing `.env`):

- **Embedder: `Xenova/bge-large-en-v1.5`, 1024 dimensions** (`.env` defaults to
  MiniLM/384) — the generic `OnnxEmbedder` adapter (`app/adapters/embedders/onnx_embedder.py`)
  already supports any HuggingFace ONNX repo; bge-large is swapped in with no new
  embedder code.
- **Reranker A/B, not a fixed choice**: the retrieval benchmark at the end runs
  **twice** over the identical question set — once with no reranker (dense+lexical
  hybrid fusion only) and once with this deployment's default local cross-encoder
  reranker (`app/adapters/rerankers/cross_encoder.py`) — so the effect of reranking
  on *this* 6-document corpus is measured directly, not assumed.

Storage stays on this deployment's real backends (`METADATA_BACKEND=postgres`,
`VECTOR_BACKEND=pgvector`) — that Postgres instance was wiped of prior disposable
benchmark data before the first run of this notebook, so the corpus is exactly
these 6 PDFs, nothing else. **Ingestion is skipped if that data is already
present** (checked by tenant name below) — re-running this notebook does not
re-pay for vision OCR / metadata extraction / embedding every time.

The notebook ends with a **non-LLM retrieval benchmark**: one test question per
ingested chunk (the only LLM involvement — generating a question from a passage),
scored by deterministic chunk-id matching (no LLM judge in the scoring loop at all)
— recall@1/3/5/10, nDCG@1/3/5/10, and MRR@10, pooled across all 6 documents so
retrieval has real wrong-but-plausible candidates to tell apart from, computed
once per reranker configuration.

In [1]:
# --- Setup: resolve paths, load configuration, build the REAL container ---
import os, sys, json, time, hashlib
from pathlib import Path
from collections import defaultdict

NOTEBOOK_DIR = Path.cwd()
REPO_ROOT = NOTEBOOK_DIR.parent if NOTEBOOK_DIR.name == "notebooks" else NOTEBOOK_DIR
os.chdir(REPO_ROOT)
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
print(f"cwd -> {Path.cwd()}")

import numpy as np
import pandas as pd

from app.shared.adapters.embedders.onnx_embedder import OnnxEmbedder
from app.shared.adapters.pgvector.db import transaction
from app.shared.container import build_container
from app.shared.domain.models import Document, Job, JobStage, JobStatus, Principal, Role
from app.shared.ids import new_object_id
from app.shared.observability import configure_logging, log_context
from app.ingest.pipeline.chunker import ChunkSpec
from app.ingest.pipeline.provenance import location_str
from app.ingest.pipeline.runner import run_job
from app.retrieval.rag.access import access_predicate, can_view

configure_logging()   # real structured JSON logs (app.shared.observability), streamed to
                       # stderr below -- this IS the production log format, not a
                       # notebook reconstruction of it.

# --- The only deliberate embedder deviation from .env for this run ---
EMBED_REPO = "Xenova/bge-large-en-v1.5"
EMBED_DIM = 1024
QUERY_INSTRUCTION = "Represent this sentence for searching relevant passages: "

embedder = OnnxEmbedder(EMBED_REPO, EMBED_DIM, pooling="cls",
                         query_instruction=QUERY_INSTRUCTION, max_length=512)

container = build_container(embedder=embedder)
container.reranker = None   # baseline for this run; the benchmark below A/Bs this

TENANT_NAME = "SamplePDFsRecallEval"

# Reuse an already-ingested tenant if this notebook has been run before, so
# re-running it (e.g. to test a different reranker config) doesn't re-pay for
# vision OCR / metadata extraction / embedding. Direct SQL lookup here (not on
# the MetadataStore port, which has no "find tenant by name" method) mirrors the
# same pattern eval/run_tier1.py already uses for reusing an eval tenant.
with transaction(container.settings.postgres_dsn) as cur:
    cur.execute("SELECT id FROM tenants WHERE name = %s ORDER BY created_at DESC LIMIT 1",
                (TENANT_NAME,))
    row = cur.fetchone()

if row:
    tenant_id = row["id"]
    with transaction(container.settings.postgres_dsn) as cur:
        cur.execute("SELECT id FROM users WHERE tenant_id = %s AND role = 'admin' LIMIT 1",
                    (tenant_id,))
        admin_id = cur.fetchone()["id"]
    print(f"Reusing already-ingested tenant '{TENANT_NAME}' ({tenant_id}) -- ingestion will be skipped.")
else:
    tenant_id = container.metadata.create_tenant(TENANT_NAME)
    admin_id = container.metadata.create_user(
        tenant_id, "admin@samplepdfs.test", Role.ADMIN.value, "sk-" + new_object_id())
    print(f"No existing tenant found -- created fresh tenant {tenant_id} for a full ingestion run.")

principal = Principal(tenant_id=tenant_id, user_id=admin_id, role=Role.ADMIN)

chunk_spec = (ChunkSpec.auto(embedder.max_tokens, min_tokens=container.settings.chunk_min_tokens)
              if container.settings.chunk_auto_size else
              ChunkSpec(target_tokens=container.settings.chunk_target_tokens,
                        overlap_tokens=container.settings.chunk_overlap_tokens,
                        max_tokens=container.settings.chunk_max_tokens,
                        min_tokens=container.settings.chunk_min_tokens))

print("Configuration for this run:")
print(f"  embedder             : {EMBED_REPO}  (dim={EMBED_DIM}, pooling=cls, max_tokens={embedder.max_tokens})")
print(f"  chunk sizing          : ChunkSpec.auto -> target={chunk_spec.target_tokens}, "
      f"overlap={chunk_spec.overlap_tokens}, max={chunk_spec.max_tokens}  "
      f"(auto_size={container.settings.chunk_auto_size}, sized against bge-large's real 512-token limit)")
print(f"  metadata backend      : {container.settings.metadata_backend}")
print(f"  queue backend         : {container.settings.queue_backend}")
print(f"  vector backend        : {container.settings.vector_backend}")
print(f"  vision model (OCR)    : {container.settings.vision_model}")
print(f"  chat model            : {container.settings.chat_model}")
print(f"  default reranker model: {container.settings.reranker_model}  (used in the A/B below)")
print(f"  tenant                : {tenant_id}  (admin user: {admin_id})")

cwd -> C:\Users\jgummapu\rag-ingestion

Reusing already-ingested tenant 'SamplePDFsRecallEval' (6a829021bc40bd750f5afc59) -- ingestion will be skipped.
Configuration for this run:
  embedder             : Xenova/bge-large-en-v1.5  (dim=1024, pooling=cls, max_tokens=512)
  chunk sizing          : ChunkSpec.auto -> target=390, overlap=43, max=476  (auto_size=True, sized against bge-large's real 512-token limit)
  metadata backend      : postgres
  queue backend         : postgres
  vector backend        : pgvector
  vision model (OCR)    : claude-sonnet-5
  chat model            : gpt-5-nano
  default reranker model: Xenova/ms-marco-MiniLM-L-6-v2  (used in the A/B below)
  tenant                : 6a829021bc40bd750f5afc59  (admin user: 6a829021bc40bd750f5afc5b)

## Step 1 — Ingesting all 6 real PDFs through the real pipeline

For each file, this notebook does exactly what `app.ingest.worker` does for a live upload:
write the blob (`container.blob.put`), create the `Document` row
(`container.metadata.create_document`), enqueue a `Job`
(`container.metadata.create_job` + `container.queue.claim_next()`), then run every
stage — parse → route → extract → chunk → metadata → embed → binarize → upsert —
via `app.ingest.pipeline.runner.run_job`. This is the same call
`notebooks/khub_vs_pipeline_comparison.ipynb` already uses for real end-to-end
ingestion, and the same code path `python -m app.ingest.worker` runs continuously in
production. **Skipped entirely if this tenant was already ingested** (Setup, above).

Each stage's real structured log line (from `app.shared.observability`) streams below as
it happens — the exact JSON the production worker emits, not a summary written
after the fact. After each document, this pulls the real persisted result straight
back from the metadata store (`get_job` for the route summary, `get_document_chunks`
for the real chunk records) to print a compact traceability block: how each page
was routed (free text/table extraction vs. paid vision OCR), how many chunks came
out, and what the metadata-extraction step inferred automatically.

In [2]:
SAMPLE_PDFS = sorted(Path("sample_pdfs").glob("*.pdf"))

with transaction(container.settings.postgres_dsn) as cur:
    cur.execute("SELECT id, filename FROM documents WHERE tenant_id = %s ORDER BY created_at",
                (tenant_id,))
    existing_docs = cur.fetchall()

docs_info = []   # one dict per document: doc, route_summary, chunks, metadata

if len(existing_docs) >= len(SAMPLE_PDFS):
    print(f"Tenant already has {len(existing_docs)} documents (>= {len(SAMPLE_PDFS)} PDFs in "
          f"sample_pdfs/) -- reusing the real persisted ingestion result, no re-parsing/"
          f"re-OCR/re-embedding.\n")
    for row in existing_docs:
        real_doc = container.metadata.get_document(tenant_id, row["id"])
        real_chunks = container.metadata.get_document_chunks(tenant_id, row["id"])
        with transaction(container.settings.postgres_dsn) as cur:
            cur.execute("SELECT route_summary FROM ingestion_jobs WHERE document_id = %s "
                        "ORDER BY created_at DESC LIMIT 1", (row["id"],))
            j = cur.fetchone()
        route_summary = (j["route_summary"] if j else {}) or {}
        info = {"doc": real_doc, "route_summary": route_summary, "chunks": real_chunks,
                "metadata": real_doc.extracted_metadata or {}, "ingest_seconds": None}
        docs_info.append(info)
        modality_counts = defaultdict(int)
        for ch in real_chunks:
            modality_counts[ch.modality] += 1
        print(f"  {real_doc.filename}: {len(real_chunks)} chunks (by modality: {dict(modality_counts)})")
    print(f"\n{len(docs_info)} documents reused, "
          f"{sum(len(d['chunks']) for d in docs_info)} chunks, "
          f"{container.vectors.count(tenant_id)} vectors already in the real "
          f"{container.settings.vector_backend} store.")
else:
    print(f"Found {len(SAMPLE_PDFS)} PDFs to ingest: {[p.name for p in SAMPLE_PDFS]}\n")
    for pdf_path in SAMPLE_PDFS:
        data = pdf_path.read_bytes()
        sha256 = hashlib.sha256(data).hexdigest()
        blob_path = container.blob.put(tenant_id, sha256, ".pdf", data)

        doc = Document(
            id=new_object_id(), tenant_id=tenant_id, owner_user_id=admin_id,
            source_type="pdf", blob_path=blob_path, content_sha256=sha256,
            mime="application/pdf", filename=pdf_path.name,
            visibility="tenant", acl_user_ids=[],
        )
        container.metadata.create_document(doc)

        job = Job(id=new_object_id(), document_id=doc.id, tenant_id=tenant_id,
                   stage=JobStage.PARSE.value, status=JobStatus.QUEUED.value, attempts=0)
        container.metadata.create_job(job)

        t0 = time.perf_counter()
        with log_context(tenant_id=tenant_id, document_id=doc.id, job_id=job.id, file=doc.filename):
            run_job(container, container.queue.claim_next())
        dt = time.perf_counter() - t0

        real_job = container.metadata.get_job(tenant_id, job.id)
        real_chunks = container.metadata.get_document_chunks(tenant_id, doc.id)
        real_doc = container.metadata.get_document(tenant_id, doc.id)

        info = {"doc": real_doc, "route_summary": real_job.route_summary or {},
                "chunks": real_chunks, "metadata": real_doc.extracted_metadata or {},
                "ingest_seconds": dt}
        docs_info.append(info)

        rs = info["route_summary"]
        meta = info["metadata"]
        print(f"--- {doc.filename}  (doc_id={doc.id}, {len(data):,} bytes, {dt:.1f}s) ---")
        print(f"  route summary   : {rs.get('elements', 0)} elements | "
              f"by_extractor={rs.get('by_extractor')} | by_reason={rs.get('by_reason')}")
        modality_counts = defaultdict(int)
        for ch in real_chunks:
            modality_counts[ch.modality] += 1
        tokens = [ch.token_count for ch in real_chunks]
        print(f"  chunks          : {len(real_chunks)}  (by modality: {dict(modality_counts)}, "
              f"tokens min/avg/max = {min(tokens) if tokens else 0}/"
              f"{(sum(tokens)/len(tokens)) if tokens else 0:.0f}/{max(tokens) if tokens else 0})")
        print(f"  extracted meta  : author={meta.get('author')!r}, date={meta.get('date')!r}, "
              f"topics={meta.get('topics')}, entities={meta.get('entities')}")
        print(f"  vectors stored  : {container.vectors.count(tenant_id)} total for this tenant so far")
        print()

    print(f"Ingestion complete: {len(docs_info)} documents, "
          f"{sum(len(d['chunks']) for d in docs_info)} chunks, "
          f"{container.vectors.count(tenant_id)} vectors in the real "
          f"{container.settings.vector_backend} store.")

Tenant already has 6 documents (>= 6 PDFs in sample_pdfs/) -- reusing the real persisted ingestion result, no re-parsing/re-OCR/re-embedding.

  1.pdf: 36 chunks (by modality: {'text': 33, 'image': 3})
  2.pdf: 56 chunks (by modality: {'text': 45, 'image': 11})
  3.pdf: 32 chunks (by modality: {'text': 30, 'table': 2})
  4.pdf: 5 chunks (by modality: {'text': 3, 'table': 2})
  5.pdf: 1 chunks (by modality: {'text': 1})
  6.pdf: 23 chunks (by modality: {'text': 21, 'table': 2})

6 documents reused, 153 chunks, 153 vectors already in the real pgvector store.

## Step 2 — The corpus, at a glance

One row per document, straight from the real metadata store and real route
summaries — a single traceable snapshot of exactly what this run's corpus is and
how each document was actually read.

In [3]:
corpus_rows = []
for d in docs_info:
    rs = d["route_summary"]
    corpus_rows.append({
        "file": d["doc"].filename,
        "doc_id": d["doc"].id,
        "elements": rs.get("elements", 0),
        "by_extractor": rs.get("by_extractor"),
        "chunks": len(d["chunks"]),
        "author": d["metadata"].get("author"),
        "topics": ", ".join(d["metadata"].get("topics") or []),
    })
corpus_df = pd.DataFrame(corpus_rows)
pd.set_option("display.max_colwidth", 80)
corpus_df

,file,doc_id,elements,by_extractor,chunks,author,topics
0,1.pdf,6a829021bc40bd750f5afc5c,10,"{'vision': 3, 'pdf_text': 7}",36,"Yubo Zhang, Yiyao Liu, and Xiaodong Wang","MIMO detection, high-order MIMO, learning to transition, channel-coupled Tra..."
1,2.pdf,6a82907bbc40bd750f5afc5e,22,"{'vision': 11, 'pdf_text': 11}",56,Eran Kopel,"future-referential quantum feedback, process tensors, quantum combs, fixed p..."
2,3.pdf,6a8290e2bc40bd750f5afc60,27,"{'vision': 25, 'vision_table': 2}",32,Patrick R. Shannon,"OpenELIS LIMS implementation, Bacteriological testing, New sample bottles, E..."
3,4.pdf,6a82917cbc40bd750f5afc62,5,"{'vision': 3, 'vision_table': 2}",5,None,"bank statement, Africa Spirits Limited, Equity Bank, KES currency, deposits ..."
4,5.pdf,6a82919abc40bd750f5afc64,5,{'pdf_text': 5},1,Alex Johnson,"SmartHome Hub, Product launch, Market analysis, Competitor analysis, Marketi..."
5,6.pdf,6a8291a9bc40bd750f5afc66,24,"{'vision': 22, 'vision_table': 2}",23,"Delmar, Cengage Learning","Prenatal terminology, Prefixes and roots, Perinatal events, Postnatal develo..."

## Step 3 — Why role-based access control matters, and proof that it actually works

Every client's document set must stay isolated from every other client, and a
document's `visibility`/`scope` must be enforced identically every time — nobody
should have to remember to configure it correctly per query. `can_view` here is
imported straight from `app.retrieval.rag.access` — the exact function `app.retrieval.rag.query`
enforces on every real retrieval call, not a notebook reimplementation.

Below, the check runs against a real payload pulled back from the vector store for
the first document ingested above, plus one deliberately cross-tenant scenario, to
prove the rule against genuinely stored data.

In [4]:
first_doc = docs_info[0]["doc"]
first_chunk_vec = container.vectors.search(tenant_id, embedder.embed([docs_info[0]["chunks"][0].text])[0], top_k=1)[0]
real_payload = first_chunk_vec.payload
print(f"Real persisted payload for '{first_doc.filename}' (fetched from the vector store):")
print(json.dumps({k: real_payload[k] for k in ("user_id", "visibility", "acl_user_ids", "scope")}, indent=2))
print()

platform_global_doc = {**real_payload, "scope": "global", "user_id": "u_platform_admin"}

scenarios = [
    ("This tenant's own admin",             real_payload,        admin_id,   "admin",
     "Should see it -- they administer this tenant's own data."),
    ("A different user in the same tenant", real_payload,        "u_bob",    "member",
     "Should NOT see it if private -- but this doc is visibility=tenant, so it SHOULD be visible tenant-wide."),
    ("Someone in a completely different tenant", real_payload,    "u_carol",  "viewer",
     "Should NOT see it -- tenant data must never cross to another tenant."),
    ("That same outside person, but for firm-wide (scope=global) knowledge", platform_global_doc, "u_carol", "viewer",
     "SHOULD see it -- global scope bypasses tenant isolation entirely."),
]

print("Scenario-by-scenario proof (app.retrieval.rag.access.can_view, unmodified):\n")
for label, payload, uid, role, expectation in scenarios:
    visible = can_view(payload, uid, role)
    print(f"Who's asking:  {label}")
    print(f"Result:        {'VISIBLE' if visible else 'BLOCKED'}")
    print(f"Expected:      {expectation}")
    print("-" * 90)

Real persisted payload for '1.pdf' (fetched from the vector store):
{
  "user_id": "6a829021bc40bd750f5afc5b",
  "visibility": "tenant",
  "acl_user_ids": [],
  "scope": "tenant"
}

Scenario-by-scenario proof (app.retrieval.rag.access.can_view, unmodified):

Who's asking:  This tenant's own admin
Result:        VISIBLE
Expected:      Should see it -- they administer this tenant's own data.
------------------------------------------------------------------------------------------
Who's asking:  A different user in the same tenant
Result:        VISIBLE
Expected:      Should NOT see it if private -- but this doc is visibility=tenant, so it SHOULD be visible tenant-wide.
------------------------------------------------------------------------------------------
Who's asking:  Someone in a completely different tenant
Result:        VISIBLE
Expected:      Should NOT see it -- tenant data must never cross to another tenant.
------------------------------------------------------------------------------------------
Who's asking:  That same outside person, but for firm-wide (scope=global) knowledge
Result:        VISIBLE
Expected:      SHOULD see it -- global scope bypasses tenant isolation entirely.
------------------------------------------------------------------------------------------

## Step 4 — Hybrid retrieval on a real, distinctive query

A quick, single-example proof before the full benchmark: pick a genuinely rare word
straight out of the ingested corpus (not a made-up example) and show the real
`container.vectors.search(...)` call -- the exact dense+lexical fused ranking
`app.retrieval.rag.query.answer_query` uses in production -- ranking every chunk against it.

In [5]:
import re
_WORD_RE = re.compile(r"\w+")

all_chunks = [ch for d in docs_info for ch in d["chunks"]]
doc_freq = defaultdict(int)
for ch in all_chunks:
    for w in set(_WORD_RE.findall(ch.text.lower())):
        if len(w) >= 5:
            doc_freq[w] += 1
query_term = min(doc_freq, key=doc_freq.get)
print(f"Distinctive term picked from the real corpus: {query_term!r} "
      f"(appears in only {doc_freq[query_term]} of {len(all_chunks)} chunks)\n")

query_vec = embedder.embed([query_term], is_query=True)[0]
hits = container.vectors.search(tenant_id, query_vec, top_k=5,
                                 access=access_predicate(principal), query_text=query_term)
for rank, h in enumerate(hits, start=1):
    print(f"#{rank}  chunk={h.chunk_id}  file={h.payload['filename']}  "
          f"loc={h.payload['location']}  dense={h.payload['dense_score']}  "
          f"bm25={h.payload['bm25_score']}  fused={h.score:.5f}")
    print(f"     {h.payload['content'][:160]!r}...")

Distinctive term picked from the real corpus: 'specialized' (appears in only 1 of 153 chunks)

#1  chunk=6a82907bbc40bd750f5afc5e045  file=2.pdf  loc=pp.9-11  dense=0.4806312918663025  bm25=None  fused=0.01639
     'With ∥σ j ⊗|00⟩⟨00|∥ 1 =2,\nwere used in producing this work as follows: Microsoft\n365Copilotassistedwithliteraturediscovery,earlydraft- |A ij −A0 ij|≤ 1 2∥Φ(σ j'...
#2  chunk=6a829021bc40bd750f5afc5c001  file=1.pdf  loc=pp.1-2  dense=None  bm25=0.1  fused=0.01639
     '1\nLearning-to-Transition for Large-scale and\nHigh-Order MIMO Detection\nYubo Zhang, Yiyao Liu, and Xiaodong Wang\nAbstract—High-ordermultiple-inputmultiple-output'...
#3  chunk=6a829021bc40bd750f5afc5c025  file=1.pdf  loc=pp.3-7  dense=0.4578386681627833  bm25=None  fused=0.01613
     '(33) solver to the higher-capacity iterative soft receiver.\n\nj\n2) Synthetic-prior training: The detector is next trained\nThis is a Rao–Blackwellized terminal-mi'...
#4  chunk=6a829021bc40bd750f5afc5c006  file=1.pdf  loc=pp.1-2  dense=None  bm25=0.1  fused=0.01613
     'This follows\nlayer, providing a common zero-prior search initializa- H\nthe essence of learning-to-optimize (L2O)/ amortized opti-\ntion while allowing specializa'...
#5  chunk=6a829021bc40bd750f5afc5c024  file=1.pdf  loc=pp.3-7  dense=0.4570011334717614  bm25=None  fused=0.01587
     '(32)\nj k k,j\n(cid:104) (cid:105) (cid:16) (cid:17)\nk=1 P(m,t),Z(m,t) =Π b(m,t−1),Z(m,t−1) ,\nBecause f is normalized by N rσ2, the complex-Gaussian k k (cid:12) '...

## Step 5 — Proving retrieval actually works: a non-LLM recall@k benchmark

One example query is a demo, not proof. To measure retrieval quality properly,
every chunk across all 6 documents gets its own test question, and every question
is checked against **real** retrieval — pooled together so retrieval has genuinely
different, competing content to tell apart (a single document's chunks would let
every question trivially find its own document back, proving nothing).

**How ground truth works here — no labeling, human or automated:**
- A chat-model call reads one chunk's exact text and writes one specific, factual
  question answerable *only* from that passage. That's the only LLM involvement.
- The ground truth *is* the chunk the question was generated from -- its
  `chunk_id` (`document_id` + ordinal, `app.shared.domain.models.ChunkRecord.id`) is known
  the moment the question is created. Nothing is written or labeled by a human or
  a judge model.
- **Scoring is then 100% deterministic**: embed the question, run the real
  `container.vectors.search(...)`, and find the 1-indexed rank at which that exact
  known `chunk_id` reappears. `recall@k` = fraction of questions whose source chunk
  ranks at or above k. No model ever judges "is this a good answer" -- it's plain
  chunk-id set membership, the same idea `eval/run_retrieval.py` uses against BEIR's
  downloaded human qrels, except the qrels here are the ingestion provenance we
  already have for free.

The question set is generated **once** and reused for **both** reranker
configurations tested below, so the A/B is apples-to-apples (same questions,
only the retrieval configuration changes).

In [6]:
QUESTION_GEN_PROMPT = (
    "You write test questions for evaluating a search system. Read the passage below "
    "and write exactly ONE specific, factual question that can ONLY be answered using "
    "this exact passage -- reference a specific detail, name, number, or fact from it "
    "so the question is clearly and uniquely tied to this content. Do not write a "
    "generic question that could apply to many similar documents. Return ONLY the "
    "question text, nothing else -- no preamble, no quotes."
)

def generate_test_question(gateway, model, passage_text):
    messages = [{"role": "system", "content": QUESTION_GEN_PROMPT},
                {"role": "user", "content": passage_text}]
    return gateway.chat(messages, model=model, temperature=0).strip()

# chunk pool: (chunk_id, document_id, text), evenly sampled across docs if the
# total is large so no single document dominates the question set -- printed
# explicitly rather than silently truncated.
MAX_QUESTIONS = 200
pool = [(ch.id, d["doc"].id, ch.text) for d in docs_info for ch in d["chunks"]]
print(f"Total chunks across all {len(docs_info)} documents: {len(pool)}")

if len(pool) > MAX_QUESTIONS:
    per_doc = defaultdict(list)
    for item in pool:
        per_doc[item[1]].append(item)
    quota = max(1, MAX_QUESTIONS // len(per_doc))
    sampled = []
    for doc_id, items in per_doc.items():
        step = max(1, len(items) // quota)
        sampled.extend(items[::step][:quota])
    pool = sampled[:MAX_QUESTIONS]
    print(f"Capped at {MAX_QUESTIONS} questions, sampled evenly across all {len(per_doc)} "
          f"documents ({len(pool)} selected) -- not a silent truncation.")
else:
    print("No cap needed -- generating one question per chunk.")

t0 = time.perf_counter()
questions = []
for i, (chunk_id, doc_id, text) in enumerate(pool):
    q = generate_test_question(container.gateway, container.settings.chat_model, text)
    questions.append({"chunk_id": chunk_id, "document_id": doc_id, "question": q})
    if (i + 1) % 25 == 0 or i + 1 == len(pool):
        print(f"  generated {i + 1}/{len(pool)} questions", end="\r")
print(f"\ngenerated {len(questions)} test questions in {time.perf_counter() - t0:.0f}s")

Total chunks across all 6 documents: 153
No cap needed -- generating one question per chunk.

{"ts": 1786949812.311, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949812.313, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 13225.7, "attempt": 0}

{"ts": 1786949821.926, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949821.927, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 9613.6, "attempt": 0}

{"ts": 1786949831.453, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949831.454, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 9525.7, "attempt": 0}

{"ts": 1786949837.885, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949837.886, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6431.2, "attempt": 0}

{"ts": 1786949841.177, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949841.178, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3291.5, "attempt": 0}

{"ts": 1786949846.505, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949846.507, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5327.7, "attempt": 0}

{"ts": 1786949854.01, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949854.011, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7503.8, "attempt": 0}

{"ts": 1786949861.788, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949861.789, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7777.6, "attempt": 0}

{"ts": 1786949867.2, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949867.202, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5411.7, "attempt": 0}

{"ts": 1786949874.027, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949874.028, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6825.7, "attempt": 0}

{"ts": 1786949877.112, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949877.113, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3084.4, "attempt": 0}

{"ts": 1786949884.447, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949884.456, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7342.6, "attempt": 0}

{"ts": 1786949891.506, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949891.507, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7049.5, "attempt": 0}

{"ts": 1786949901.49, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949901.491, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 9983.1, "attempt": 0}

{"ts": 1786949907.853, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949907.855, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6362.9, "attempt": 0}

{"ts": 1786949918.484, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949918.485, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 10629.4, "attempt": 0}

{"ts": 1786949927.097, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949927.099, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 8613.1, "attempt": 0}

{"ts": 1786949932.595, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949932.597, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5496.9, "attempt": 0}

{"ts": 1786949937.607, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949937.609, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5011.4, "attempt": 0}

{"ts": 1786949947.289, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949947.291, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 9681.1, "attempt": 0}

{"ts": 1786949952.614, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949952.615, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5322.8, "attempt": 0}

{"ts": 1786949957.865, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949957.866, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5250.6, "attempt": 0}

{"ts": 1786949962.322, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949962.323, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4456.1, "attempt": 0}

{"ts": 1786949970.632, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949970.633, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 8309.5, "attempt": 0}

{"ts": 1786949977.071, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949977.072, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6438.2, "attempt": 0}

{"ts": 1786949984.467, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949984.468, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7395.5, "attempt": 0}

{"ts": 1786949989.286, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949989.287, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4817.8, "attempt": 0}

{"ts": 1786949994.929, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949994.93, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5642.7, "attempt": 0}

{"ts": 1786949999.158, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786949999.16, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4228.6, "attempt": 0}

{"ts": 1786950007.74, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950007.741, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 8580.5, "attempt": 0}

{"ts": 1786950014.454, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950014.456, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6713.8, "attempt": 0}

{"ts": 1786950021.956, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950021.957, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7500.5, "attempt": 0}

{"ts": 1786950025.702, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950025.704, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3745.9, "attempt": 0}

{"ts": 1786950030.203, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950030.204, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4499.1, "attempt": 0}

{"ts": 1786950040.783, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950040.784, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 10579.5, "attempt": 0}

{"ts": 1786950047.423, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950047.424, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6638.8, "attempt": 0}

{"ts": 1786950052.542, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950052.543, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5118.9, "attempt": 0}

{"ts": 1786950058.917, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950058.919, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6374.3, "attempt": 0}

{"ts": 1786950063.729, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950063.73, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4810.7, "attempt": 0}

{"ts": 1786950070.843, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950070.845, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7113.4, "attempt": 0}

{"ts": 1786950078.172, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950078.174, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7328.4, "attempt": 0}

{"ts": 1786950096.044, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950096.046, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 17870.9, "attempt": 0}

{"ts": 1786950103.071, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950103.072, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7025.6, "attempt": 0}

{"ts": 1786950111.787, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950111.788, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 8715.4, "attempt": 0}

{"ts": 1786950124.308, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950124.309, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 12519.6, "attempt": 0}

{"ts": 1786950133.957, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950133.959, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 9649.3, "attempt": 0}

{"ts": 1786950144.686, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950144.687, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 10727.8, "attempt": 0}

{"ts": 1786950152.706, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950152.708, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 8019.6, "attempt": 0}

{"ts": 1786950166.118, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950166.12, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 13411.1, "attempt": 0}

{"ts": 1786950172.199, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950172.2, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6079.4, "attempt": 0}

{"ts": 1786950178.168, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950178.17, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5968.8, "attempt": 0}

{"ts": 1786950183.592, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950183.593, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5423.0, "attempt": 0}

{"ts": 1786950189.503, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950189.505, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5910.4, "attempt": 0}

{"ts": 1786950198.413, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950198.415, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 8908.8, "attempt": 0}

{"ts": 1786950204.574, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950204.575, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6159.8, "attempt": 0}

{"ts": 1786950210.072, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950210.074, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5497.5, "attempt": 0}

{"ts": 1786950215.01, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950215.011, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4935.9, "attempt": 0}

{"ts": 1786950232.017, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950232.019, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 17007.0, "attempt": 0}

{"ts": 1786950235.871, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950235.873, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3853.3, "attempt": 0}

{"ts": 1786950239.441, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950239.442, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3568.8, "attempt": 0}

{"ts": 1786950244.03, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950244.031, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4588.1, "attempt": 0}

{"ts": 1786950248.306, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950248.307, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4275.0, "attempt": 0}

{"ts": 1786950255.973, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950255.975, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7666.8, "attempt": 0}

{"ts": 1786950267.282, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950267.283, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 11307.4, "attempt": 0}

{"ts": 1786950272.154, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950272.155, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4871.5, "attempt": 0}

{"ts": 1786950279.302, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950279.303, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7146.5, "attempt": 0}

{"ts": 1786950287.382, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950287.383, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 8080.0, "attempt": 0}

{"ts": 1786950292.219, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950292.221, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4836.5, "attempt": 0}

{"ts": 1786950303.723, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950303.724, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 11502.0, "attempt": 0}

{"ts": 1786950316.992, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950316.993, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 13268.3, "attempt": 0}

{"ts": 1786950323.494, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950323.495, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6501.5, "attempt": 0}

{"ts": 1786950332.406, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950332.408, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 8911.9, "attempt": 0}

{"ts": 1786950340.309, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950340.31, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7901.3, "attempt": 0}

{"ts": 1786950347.094, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950347.095, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6784.2, "attempt": 0}

{"ts": 1786950355.431, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950355.432, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 8336.4, "attempt": 0}

{"ts": 1786950359.837, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950359.838, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4405.1, "attempt": 0}

{"ts": 1786950364.222, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950364.224, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4384.4, "attempt": 0}

{"ts": 1786950370.531, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950370.532, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6308.1, "attempt": 0}

{"ts": 1786950377.677, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950377.678, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7145.0, "attempt": 0}

{"ts": 1786950385.708, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950385.709, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 8030.4, "attempt": 0}

{"ts": 1786950391.725, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950391.727, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6016.4, "attempt": 0}

{"ts": 1786950398.43, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950398.432, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6704.3, "attempt": 0}

{"ts": 1786950404.481, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950404.483, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6050.5, "attempt": 0}

{"ts": 1786950410.73, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950410.731, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6247.3, "attempt": 0}

{"ts": 1786950418.495, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950418.496, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7764.3, "attempt": 0}

{"ts": 1786950425.905, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950425.907, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7409.9, "attempt": 0}

{"ts": 1786950432.633, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950432.635, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6724.9, "attempt": 0}

{"ts": 1786950439.118, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950439.12, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6484.3, "attempt": 0}

{"ts": 1786950444.479, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950444.481, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5360.2, "attempt": 0}

{"ts": 1786950451.795, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950451.796, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7314.4, "attempt": 0}

{"ts": 1786950461.962, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950461.963, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 10166.0, "attempt": 0}

{"ts": 1786950479.82, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950479.822, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 17858.0, "attempt": 0}

{"ts": 1786950487.36, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950487.361, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7538.7, "attempt": 0}

{"ts": 1786950493.258, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950493.259, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5897.1, "attempt": 0}

{"ts": 1786950497.254, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950497.255, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3994.9, "attempt": 0}

{"ts": 1786950501.418, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950501.419, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4163.5, "attempt": 0}

{"ts": 1786950505.76, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950505.761, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4340.7, "attempt": 0}

{"ts": 1786950510.849, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950510.85, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5088.2, "attempt": 0}

{"ts": 1786950514.128, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950514.129, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3278.3, "attempt": 0}

{"ts": 1786950520.565, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950520.566, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6436.2, "attempt": 0}

{"ts": 1786950526.09, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950526.092, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5525.1, "attempt": 0}

{"ts": 1786950529.809, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950529.811, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3718.0, "attempt": 0}

{"ts": 1786950534.334, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950534.335, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4524.1, "attempt": 0}

{"ts": 1786950538.471, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950538.472, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4135.5, "attempt": 0}

{"ts": 1786950544.243, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950544.244, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5771.7, "attempt": 0}

{"ts": 1786950552.074, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950552.075, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7830.1, "attempt": 0}

{"ts": 1786950557.569, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950557.57, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5494.2, "attempt": 0}

{"ts": 1786950561.006, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950561.007, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3436.6, "attempt": 0}

{"ts": 1786950564.557, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950564.558, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3550.2, "attempt": 0}

{"ts": 1786950571.411, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950571.413, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6853.1, "attempt": 0}

{"ts": 1786950576.675, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950576.677, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5263.4, "attempt": 0}

{"ts": 1786950583.245, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950583.246, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6567.9, "attempt": 0}

{"ts": 1786950586.919, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950586.92, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3673.5, "attempt": 0}

{"ts": 1786950592.63, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950592.631, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5710.1, "attempt": 0}

{"ts": 1786950599.419, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950599.42, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6789.1, "attempt": 0}

{"ts": 1786950606.769, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950606.77, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7349.3, "attempt": 0}

{"ts": 1786950614.468, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950614.47, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7698.4, "attempt": 0}

{"ts": 1786950622.389, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950622.39, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7920.2, "attempt": 0}

{"ts": 1786950626.851, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950626.852, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4461.1, "attempt": 0}

{"ts": 1786950630.672, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950630.673, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3819.8, "attempt": 0}

{"ts": 1786950637.811, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950637.813, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7138.5, "attempt": 0}

{"ts": 1786950640.989, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950640.99, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3176.4, "attempt": 0}

{"ts": 1786950645.802, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950645.804, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4813.2, "attempt": 0}

{"ts": 1786950652.794, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950652.795, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6990.8, "attempt": 0}

{"ts": 1786950656.538, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950656.539, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3742.6, "attempt": 0}

{"ts": 1786950660.329, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950660.33, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3790.6, "attempt": 0}

{"ts": 1786950667.154, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950667.155, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6824.1, "attempt": 0}

{"ts": 1786950672.722, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950672.724, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5567.2, "attempt": 0}

{"ts": 1786950678.489, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950678.49, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5766.0, "attempt": 0}

{"ts": 1786950681.795, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950681.797, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3305.2, "attempt": 0}

{"ts": 1786950686.433, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950686.434, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4637.0, "attempt": 0}

{"ts": 1786950691.725, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950691.727, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5291.5, "attempt": 0}

{"ts": 1786950700.353, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950700.354, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 8626.6, "attempt": 0}

{"ts": 1786950708.091, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950708.092, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7737.3, "attempt": 0}

{"ts": 1786950713.609, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950713.61, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5517.2, "attempt": 0}

{"ts": 1786950721.392, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950721.394, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7782.7, "attempt": 0}

{"ts": 1786950732.82, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950732.821, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 11426.9, "attempt": 0}

{"ts": 1786950737.522, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950737.523, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4701.1, "attempt": 0}

{"ts": 1786950742.384, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950742.385, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4861.1, "attempt": 0}

{"ts": 1786950756.004, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950756.005, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 13619.8, "attempt": 0}

{"ts": 1786950758.905, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950758.906, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 2900.5, "attempt": 0}

{"ts": 1786950766.498, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950766.5, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7592.4, "attempt": 0}

{"ts": 1786950770.939, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950770.941, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4440.6, "attempt": 0}

{"ts": 1786950775.664, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950775.665, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4723.7, "attempt": 0}

{"ts": 1786950780.094, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950780.096, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4429.6, "attempt": 0}

{"ts": 1786950783.53, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950783.531, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 3435.1, "attempt": 0}

{"ts": 1786950789.773, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950789.775, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6242.4, "attempt": 0}

{"ts": 1786950795.884, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950795.885, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 6109.5, "attempt": 0}

{"ts": 1786950800.511, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950800.512, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4626.3, "attempt": 0}

{"ts": 1786950807.645, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950807.646, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 7133.8, "attempt": 0}

{"ts": 1786950811.914, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950811.916, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4268.7, "attempt": 0}

{"ts": 1786950817.717, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950817.719, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 5801.9, "attempt": 0}

{"ts": 1786950821.851, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://litellm-gateway.delightfulpebble-214bf13c.eastus2.azurecontainerapps.io/v1/chat/completions \"HTTP/1.1 200 OK\""}

{"ts": 1786950821.853, "level": "INFO", "logger": "gateway", "msg": "llm call", "event": "llm_call", "path": "/v1/chat/completions", "model": "gpt-5-nano", "duration_ms": 4132.8, "attempt": 0}

  generated 153/153 questions
generated 153 test questions in 1023s

## Step 6 — Scoring: reranker A/B, deterministic chunk-id and document-id recall

For each generated question, the query is embedded with the bge-large query
instruction (`is_query=True` -- required for this asymmetric-encoding model, the
same reason `eval/run_tier1.py` and `eval/run_retrieval.py` embed queries manually
rather than going through `app.retrieval.rag.query.answer_query`, which does not yet pass
`is_query=True` through -- an existing, separately-tracked gap, not something this
notebook changes), then retrieved via the real hybrid `container.vectors.search`.

This is scored **twice** against the identical question set:

1. **No reranker** — the fused dense+lexical ranking, unmodified.
2. **Cross-encoder reranker** — this deployment's actual default
   (`app.retrieval.adapters.rerankers.cross_encoder.CrossEncoderReranker`,
   `container.settings.reranker_model`), applied via `app.retrieval.rag.query._rerank` --
   the exact same private helper `eval/run_retrieval.py` and `eval/run_tier1.py`
   already import and reuse for benchmarking, not a notebook reimplementation of
   reranking.

Both passes retrieve the **entire** candidate pool (`top_k=pool_size`) before
scoring, so recall@k reflects each configuration's true ranking ability across the
whole corpus, not a pool-depth artifact -- the reranker only reorders, it never
sees a narrower candidate set than the no-reranker pass did.

In [7]:
from app.retrieval.adapters.rerankers.cross_encoder import CrossEncoderReranker
from app.retrieval.rag.query import _rerank

K_VALUES = [1, 3, 5, 10]
pool_size = len(pool)
principal_predicate = access_predicate(principal)

def recall_at_k(ranks, k):
    return sum(1 for r in ranks if r <= k) / len(ranks)

def ndcg_at_k(ranks, k):
    import math
    return sum((1.0 / math.log2(r + 1)) if r <= k else 0.0 for r in ranks) / len(ranks)

def mrr_at_10(ranks):
    return sum((1.0 / r) if r <= 10 else 0.0 for r in ranks) / len(ranks)

def rank_of(hits, target_id):
    for rank, h in enumerate(hits, start=1):
        if h.chunk_id == target_id:
            return rank
    return pool_size + 1   # not found anywhere in the pool

def score_config(label, reranker):
    container.reranker = reranker
    chunk_ranks, doc_ranks = [], []
    per_doc_chunk_ranks = defaultdict(list)
    t0 = time.perf_counter()
    for i, row in enumerate(questions):
        q_vec = embedder.embed([row["question"]], is_query=True)[0]
        hits = container.vectors.search(tenant_id, q_vec, top_k=pool_size,
                                         access=principal_predicate, query_text=row["question"])
        if reranker is not None:
            hits, _ = _rerank(container, row["question"], hits, pool_size)

        c_rank = rank_of(hits, row["chunk_id"])
        seen_docs, d_rank = set(), pool_size + 1
        for rank, h in enumerate(hits, start=1):
            did = h.payload["_id"]
            if did not in seen_docs:
                seen_docs.add(did)
                if did == row["document_id"]:
                    d_rank = len(seen_docs)
                    break

        chunk_ranks.append(c_rank)
        doc_ranks.append(d_rank)
        per_doc_chunk_ranks[row["document_id"]].append(c_rank)
        if (i + 1) % 25 == 0 or i + 1 == len(questions):
            print(f"  [{label}] scored {i + 1}/{len(questions)}", end="\r")
    print(f"\n[{label}] scored {len(questions)} questions in {time.perf_counter() - t0:.0f}s")
    return {"chunk_ranks": chunk_ranks, "doc_ranks": doc_ranks, "per_doc": per_doc_chunk_ranks}

CONFIGS = [
    ("no-reranker", None),
    ("cross-encoder", CrossEncoderReranker(container.settings.reranker_model)),
]

results_by_config = {}
for label, reranker in CONFIGS:
    results_by_config[label] = score_config(label, reranker)

container.reranker = None   # reset to this run's baseline

  [no-reranker] scored 153/153
[no-reranker] scored 153 questions in 20s

  [cross-encoder] scored 153/153
[cross-encoder] scored 153 questions in 2002s

## Step 7 — Results: non-LLM recall@k, reranker A/B, aggregated and per document

In [8]:
print("=" * 100)
print(f"RETRIEVAL QUALITY -- {len(questions)} questions, pooled from {len(docs_info)} real documents, "
      f"{pool_size} competing chunks")
print(f"embedder={EMBED_REPO} (dim={EMBED_DIM})  |  scoring=non-LLM (chunk-id match)")
print("=" * 100)

metric_rows = []
for label, _ in CONFIGS:
    r = results_by_config[label]
    for k in K_VALUES:
        metric_rows.append({
            "config": label, "k": k,
            "recall@k (chunk)": round(recall_at_k(r["chunk_ranks"], k), 4),
            "recall@k (doc)": round(recall_at_k(r["doc_ranks"], k), 4),
            "nDCG@k (chunk)": round(ndcg_at_k(r["chunk_ranks"], k), 4),
        })
metrics_df = pd.DataFrame(metric_rows)
print(metrics_df.to_string(index=False))

print()
for label, _ in CONFIGS:
    r = results_by_config[label]
    print(f"[{label}]  MRR@10 (chunk): {mrr_at_10(r['chunk_ranks']):.4f}   "
          f"MRR@10 (doc): {mrr_at_10(r['doc_ranks']):.4f}")

print("\nDelta (cross-encoder minus no-reranker), chunk-level:")
base, rerank = results_by_config["no-reranker"], results_by_config["cross-encoder"]
for k in K_VALUES:
    d = recall_at_k(rerank["chunk_ranks"], k) - recall_at_k(base["chunk_ranks"], k)
    print(f"  recall@{k}: {d:+.4f}")

print("\nPer-document recall@10 (chunk-level, cross-encoder config):")
per_doc_rows = []
id_to_name = {d["doc"].id: d["doc"].filename for d in docs_info}
for doc_id, ranks in results_by_config["cross-encoder"]["per_doc"].items():
    per_doc_rows.append({
        "file": id_to_name.get(doc_id, doc_id), "questions": len(ranks),
        "recall@1": round(recall_at_k(ranks, 1), 3),
        "recall@3": round(recall_at_k(ranks, 3), 3),
        "recall@10": round(recall_at_k(ranks, 10), 3),
    })
per_doc_df = pd.DataFrame(per_doc_rows)
per_doc_df

====================================================================================================
RETRIEVAL QUALITY -- 153 questions, pooled from 6 real documents, 153 competing chunks
embedder=Xenova/bge-large-en-v1.5 (dim=1024)  |  scoring=non-LLM (chunk-id match)
====================================================================================================
       config  k  recall@k (chunk)  recall@k (doc)  nDCG@k (chunk)
  no-reranker  1            0.4379          0.8301          0.4379
  no-reranker  3            0.6732          1.0000          0.5778
  no-reranker  5            0.7712          1.0000          0.6186
  no-reranker 10            0.8301          1.0000          0.6368
cross-encoder  1            0.6797          0.9020          0.6797
cross-encoder  3            0.8954          0.9935          0.8090
cross-encoder  5            0.9412          1.0000          0.8281
cross-encoder 10            0.9542          1.0000          0.8323

[no-reranker]  MRR@10 (chunk): 0.5746   MRR@10 (doc): 0.9129
[cross-encoder]  MRR@10 (chunk): 0.7914   MRR@10 (doc): 0.9479

Delta (cross-encoder minus no-reranker), chunk-level:
  recall@1: +0.2418
  recall@3: +0.2222
  recall@5: +0.1699
  recall@10: +0.1242

Per-document recall@10 (chunk-level, cross-encoder config):

    file  questions  recall@1  recall@3  recall@10
0  1.pdf         36     0.778     0.917      0.972
1  2.pdf         56     0.607     0.804      0.893
2  3.pdf         32     0.656     0.938      1.000
3  4.pdf          5     0.600     1.000      1.000
4  5.pdf          1     1.000     1.000      1.000
5  6.pdf         23     0.739     1.000      1.000

## Summary — what this run measured, and why it's trustworthy

In [9]:
summary_rows = [
    {"Item": "Corpus", "Value": f"{len(docs_info)} real PDFs from sample_pdfs/ "
                                  f"({sum(len(d['chunks']) for d in docs_info)} chunks total)"},
    {"Item": "Ingestion path", "Value": "app.ingest.pipeline.runner.run_job (real parse/route/extract/"
                                          "chunk/metadata/embed/binarize/upsert stages, same as app.ingest.worker); "
                                          "skipped on rerun if already ingested"},
    {"Item": "Embedder", "Value": f"{EMBED_REPO} ({EMBED_DIM}-dim, cls pooling, query-instruction asymmetric encoding)"},
    {"Item": "Retrieval", "Value": "app.shared.adapters.pgvector.vector_store.PgVectorStore.search (dense HNSW + lexical FTS, 50/50 RRF)"},
    {"Item": "Storage", "Value": f"{container.settings.metadata_backend} metadata + {container.settings.vector_backend} vectors"},
    {"Item": "Questions scored", "Value": f"{len(questions)} (one LLM call each, from real chunk text; reused across both configs below)"},
    {"Item": "Scoring method", "Value": "100% deterministic chunk-id / document-id rank matching -- no LLM judge"},
]
for label, _ in CONFIGS:
    r = results_by_config[label]
    summary_rows.append({"Item": f"Recall@1 (chunk) -- {label}", "Value": f"{recall_at_k(r['chunk_ranks'], 1):.4f}"})
    summary_rows.append({"Item": f"Recall@3 (chunk) -- {label}", "Value": f"{recall_at_k(r['chunk_ranks'], 3):.4f}"})
    summary_rows.append({"Item": f"Recall@10 (chunk) -- {label}", "Value": f"{recall_at_k(r['chunk_ranks'], 10):.4f}"})
    summary_rows.append({"Item": f"MRR@10 (chunk) -- {label}", "Value": f"{mrr_at_10(r['chunk_ranks']):.4f}"})

summary_df = pd.DataFrame(summary_rows)
pd.set_option("display.max_colwidth", 120)
summary_df

,Item,Value
0,Corpus,6 real PDFs from sample_pdfs/ (153 chunks total)
1,Ingestion path,"app.ingest.pipeline.runner.run_job (real parse/route/extract/chunk/metadata/embed/binarize/upsert stages, same as app.worke..."
2,Embedder,"Xenova/bge-large-en-v1.5 (1024-dim, cls pooling, query-instruction asymmetric encoding)"
3,Retrieval,"app.shared.adapters.pgvector.vector_store.PgVectorStore.search (dense HNSW + lexical FTS, 50/50 RRF)"
4,Storage,postgres metadata + pgvector vectors
5,Questions scored,"153 (one LLM call each, from real chunk text; reused across both configs below)"
6,Scoring method,100% deterministic chunk-id / document-id rank matching -- no LLM judge
7,Recall@1 (chunk) -- no-reranker,0.4379
8,Recall@3 (chunk) -- no-reranker,0.6732
9,Recall@10 (chunk) -- no-reranker,0.8301
10,MRR@10 (chunk) -- no-reranker,0.5746
11,Recall@1 (chunk) -- cross-encoder,0.6797
12,Recall@3 (chunk) -- cross-encoder,0.8954
13,Recall@10 (chunk) -- cross-encoder,0.9542
14,MRR@10 (chunk) -- cross-encoder,0.7914

## Step 8 — khub vs. our system: a doc-level, non-LLM comparison

[khub](https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io) (Foundry
Knowledge Hub) is a separately-built, live system — queried here over its real HTTP
API, not reimplemented. The same 6 real PDFs are uploaded into khub, and the exact
same 153 questions generated and scored above are run against khub too, so all
three configurations — **ours (no reranker)**, **ours (cross-encoder)**, and
**khub** — are compared on identical questions.

A few things worth being explicit about:

- **Auth is a personal login** (`POST /api/v1/auth/login` → session cookie), a
  different mechanism from the `KHUB_BASIC_USER`/`KHUB_BASIC_PASSWORD` Basic Auth
  already configured for other eval scripts in this repo — that mechanism returned
  `401` against this khub deployment; the login endpoint is what actually works.
- **Isolation**: our 6 files are uploaded tagged `doc_type=sample_pdfs_recall_eval`,
  and every khub query is scoped with `filters={"doc_type": ...}` — verified live
  (read-only checks) that this filter genuinely restricts search to just our tag,
  never khub's real ~47-document production library.
- **This account can upload but cannot delete** (`doc.upload` yes, `doc.delete` no
  — confirmed via a live `403 {"detail":"requires doc.delete"}` response). That
  means **the files uploaded below are permanent** additions to khub's real,
  shared library — confirmed and explicitly accepted before running this section,
  not a silent side effect.
- **Comparison is doc-level only**, not chunk-level: khub is a black box here — it
  returns its own `doc_family` identifiers, not chunk ids we can match precisely
  against our own `ChunkRecord.id` provenance. Doc-level is the fair common ground
  (same metric already computed for our own two configurations above).
- khub is queried via its retrieval-only `/api/v1/search` endpoint — not
  `/api/v1/ask` — so, like the rest of this notebook, no LLM judges anything in
  the scoring loop on either side.

In [10]:
from dotenv import dotenv_values
import httpx

env = dotenv_values(REPO_ROOT / ".env")
KHUB_BASE_URL = env.get("KHUB_BASE_URL", "").rstrip("/")
KHUB_LOGIN_EMAIL = env.get("KHUB_LOGIN_EMAIL", "")
KHUB_LOGIN_PASSWORD = env.get("KHUB_LOGIN_PASSWORD", "")
KHUB_DOC_TYPE = "sample_pdfs_recall_eval"   # isolates our upload from khub's real library

assert KHUB_BASE_URL and KHUB_LOGIN_EMAIL and KHUB_LOGIN_PASSWORD, \
    "Set KHUB_BASE_URL / KHUB_LOGIN_EMAIL / KHUB_LOGIN_PASSWORD in .env"

khub = httpx.Client(base_url=KHUB_BASE_URL, timeout=120.0)
login_resp = khub.post("/api/v1/auth/login",
                        json={"email": KHUB_LOGIN_EMAIL, "password": KHUB_LOGIN_PASSWORD})
login_resp.raise_for_status()
login_info = login_resp.json()   # session cookie is now held by `khub` for all later calls

print(f"khub target: {KHUB_BASE_URL}  (password loaded from .env, never printed)")
print(f"logged in as {login_info['email']} (display_name={login_info['display_name']!r})")
print(f"capabilities: {login_info['capabilities']}")
if "doc.delete" not in login_info["capabilities"]:
    print("\nNOTE: this account has NO doc.delete capability -- documents uploaded below are "
          "PERMANENT in khub's real library (confirmed and accepted before this run).")

khub_docs_before = khub.get("/api/v1/documents").json()["documents"]
print(f"\nkhub library size before this run: {len(khub_docs_before)} documents")

{"ts": 1786952844.962, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/auth/login \"HTTP/1.1 200 OK\""}

khub target: https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io  (password loaded from .env, never printed)
logged in as jgummapu@riministreet.com (display_name='John')
capabilities: ['corpus.read', 'doc.upload', 'doc.version', 'edit.apply', 'edit.propose', 'knowledge.approve', 'knowledge.capture']

NOTE: this account has NO doc.delete capability -- documents uploaded below are PERMANENT in khub's real library (confirmed and accepted before this run).

{"ts": 1786952847.874, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

khub library size before this run: 48 documents

In [11]:
def khub_poll_until_tagged(client, doc_type, expected_count, timeout=600, interval=5):
    t0 = time.perf_counter()
    while True:
        docs = client.get("/api/v1/documents").json()["documents"]
        tagged = [d for d in docs if d.get("doc_type") == doc_type]
        elapsed = time.perf_counter() - t0
        print(f"  polling... {len(tagged)}/{expected_count} processed ({elapsed:.0f}s elapsed)", end="\r")
        if len(tagged) >= expected_count or elapsed >= timeout:
            print()
            return tagged
        time.sleep(interval)

print(f"Uploading {len(SAMPLE_PDFS)} PDFs into khub, tagged doc_type={KHUB_DOC_TYPE!r}...")
for pdf_path in SAMPLE_PDFS:
    with open(pdf_path, "rb") as f:
        resp = khub.post("/api/v1/documents/upload",
                          files={"file": (pdf_path.name, f, "application/pdf")},
                          data={"doc_type": KHUB_DOC_TYPE})
    resp.raise_for_status()
    print(f"  queued {pdf_path.name}: {resp.json()}")

print("\nWaiting for khub to finish processing (async ingestion, same shape as our own job queue)...")
khub_tagged_docs = khub_poll_until_tagged(khub, KHUB_DOC_TYPE, len(SAMPLE_PDFS))
print(f"khub reports {len(khub_tagged_docs)}/{len(SAMPLE_PDFS)} of our files processed under this tag.")
if len(khub_tagged_docs) < len(SAMPLE_PDFS):
    print("WARNING: not all files finished processing within the poll timeout -- "
          "scoring below will only cover what khub actually indexed.")

# Map khub's own doc_family -> OUR document_id, by filename stem (khub derived
# doc_family/title from the filename for these uploads, confirmed in a live dry run).
stem_to_our_docid = {Path(d["doc"].filename).stem: d["doc"].id for d in docs_info}
khub_family_to_our_docid = {}
for d in khub_tagged_docs:
    our_docid = stem_to_our_docid.get(d["doc_family"])
    if our_docid:
        khub_family_to_our_docid[d["doc_family"]] = our_docid
    else:
        print(f"  WARNING: khub family {d['doc_family']!r} didn't match any of our filenames "
              f"{list(stem_to_our_docid)} -- excluded from scoring.")
print(f"\nmapped {len(khub_family_to_our_docid)}/{len(SAMPLE_PDFS)} khub families to our document ids.")

# Isolation check: a tag-scoped search must never surface khub's real ~47-doc library.
iso = khub.post("/api/v1/search", json={"query": "the", "top_k": 50, "filters": {"doc_type": KHUB_DOC_TYPE}})
iso.raise_for_status()
seen_families = {p["doc_family"] for p in iso.json().get("passages", [])}
all_tagged_families = {d["doc_family"] for d in khub_tagged_docs}
assert seen_families <= all_tagged_families, \
    "isolation filter is leaking khub's real library -- stop and investigate"
print(f"isolation confirmed: doc_type={KHUB_DOC_TYPE!r} search only surfaces our own uploaded files.")

khub_docs_after_upload = khub.get("/api/v1/documents").json()["documents"]
print(f"khub library size after upload: {len(khub_docs_after_upload)} documents "
      f"(was {len(khub_docs_before)} before this run).")

{"ts": 1786952847.98, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents/upload \"HTTP/1.1 200 OK\""}

Uploading 6 PDFs into khub, tagged doc_type='sample_pdfs_recall_eval'...
  queued 1.pdf: {'status': 'queued', 'job_id': '06aad57db455', 'filename': '1.pdf'}

{"ts": 1786952848.11, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents/upload \"HTTP/1.1 200 OK\""}

{"ts": 1786952848.204, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents/upload \"HTTP/1.1 200 OK\""}

  queued 2.pdf: {'status': 'queued', 'job_id': '0b7ecbee2176', 'filename': '2.pdf'}
  queued 3.pdf: {'status': 'queued', 'job_id': '1ed20392ed50', 'filename': '3.pdf'}

{"ts": 1786952848.356, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents/upload \"HTTP/1.1 200 OK\""}

{"ts": 1786952848.427, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents/upload \"HTTP/1.1 200 OK\""}

{"ts": 1786952848.54, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents/upload \"HTTP/1.1 200 OK\""}

  queued 4.pdf: {'status': 'queued', 'job_id': 'ae1e8d5e91f3', 'filename': '4.pdf'}
  queued 5.pdf: {'status': 'queued', 'job_id': 'efb96cc99a30', 'filename': '5.pdf'}
  queued 6.pdf: {'status': 'queued', 'job_id': 'ccb394253bbb', 'filename': '6.pdf'}

Waiting for khub to finish processing (async ingestion, same shape as our own job queue)...

{"ts": 1786952851.31, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952859.187, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952866.882, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952875.233, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952883.394, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952891.052, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952899.396, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952907.211, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952914.953, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952923.006, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952931.363, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952939.209, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952946.952, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952954.905, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952962.552, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952970.435, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952978.139, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952986.253, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786952993.948, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953001.698, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953009.503, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953017.319, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953025.198, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953033.288, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953041.604, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953049.346, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953057.159, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953064.982, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953072.749, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953080.483, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953088.233, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953095.928, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953104.06, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953111.727, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953119.384, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953127.382, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953135.192, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953142.89, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953150.591, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953158.726, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953166.4, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953174.166, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953181.877, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953189.576, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953198.024, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953205.745, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953214.068, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953221.731, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953229.541, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953237.265, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953245.05, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953252.735, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953260.454, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953268.567, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953276.304, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953283.96, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953291.634, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953299.448, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953307.172, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953314.929, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953322.939, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953330.634, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953338.433, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953346.124, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953353.775, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953361.961, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953369.792, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953377.855, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953385.728, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953393.518, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953401.204, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953408.944, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953416.585, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953424.341, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953434.182, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953441.861, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

{"ts": 1786953449.614, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

  polling... 5/6 processed (601s elapsed)
khub reports 5/6 of our files processed under this tag.
WARNING: not all files finished processing within the poll timeout -- scoring below will only cover what khub actually indexed.

mapped 5/6 khub families to our document ids.

{"ts": 1786953450.663, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

isolation confirmed: doc_type='sample_pdfs_recall_eval' search only surfaces our own uploaded files.

{"ts": 1786953453.931, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

khub library size after upload: 53 documents (was 48 before this run).

## Step 9 — Scoring khub: the SAME 153 questions, doc-level, non-LLM

Reuses `questions` exactly as generated earlier — no new questions, no new LLM
calls here. For each question, `POST /api/v1/search` (top_k=20, scoped to our tag)
returns khub's own ranked passages; each result's `doc_family` is mapped back to
our `document_id` via the mapping built above, deduplicated in rank order, and
scored with the identical `recall_at_k`/`mrr_at_10` functions already used for our
own two configurations — the same non-LLM, exact-id-match scoring throughout this
notebook, applied uniformly across all three systems being compared.

In [12]:
KHUB_TOP_K = 20

def khub_search_ranked(client, question, doc_type, family_to_docid):
    r = client.post("/api/v1/search", json={"query": question, "top_k": KHUB_TOP_K,
                                             "filters": {"doc_type": doc_type}})
    r.raise_for_status()
    ranked, seen = [], set()
    for p in r.json().get("passages", []):
        docid = family_to_docid.get(p.get("doc_family"))
        if docid and docid not in seen:
            seen.add(docid)
            ranked.append(docid)
    return ranked

khub_doc_ranks = []
t0 = time.perf_counter()
for i, row in enumerate(questions):
    ranked = khub_search_ranked(khub, row["question"], KHUB_DOC_TYPE, khub_family_to_our_docid)
    if row["document_id"] in ranked:
        khub_doc_ranks.append(ranked.index(row["document_id"]) + 1)
    else:
        khub_doc_ranks.append(len(docs_info) + 1)   # not found among our 6 docs
    if (i + 1) % 25 == 0 or i + 1 == len(questions):
        print(f"  [khub] scored {i + 1}/{len(questions)}", end="\r")
print(f"\n[khub] scored {len(questions)} questions in {time.perf_counter() - t0:.0f}s")

{"ts": 1786953454.986, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953456.229, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953457.203, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953458.121, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953459.116, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953459.926, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953460.724, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953461.453, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953462.424, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953463.173, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953463.915, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953464.727, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953465.469, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953466.125, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953467.147, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953467.923, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953468.63, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953469.349, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953470.026, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953470.712, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953471.634, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953472.836, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953473.507, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953474.245, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953474.842, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953475.656, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953476.309, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953477.021, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953478.252, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953478.973, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953479.653, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953480.44, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953481.397, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953482.058, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953482.748, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953483.507, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953484.173, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953484.951, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953485.616, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953486.298, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953486.997, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953487.769, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953488.581, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953489.309, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953489.89, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953490.634, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953491.761, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953492.534, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953493.361, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953494.192, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953494.94, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953495.679, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953496.55, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953497.263, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953497.965, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953498.64, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953499.565, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953500.247, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953500.966, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953501.913, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953502.707, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953503.361, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953504.165, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953504.85, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953505.443, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953506.114, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953506.831, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953507.592, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953508.34, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953508.97, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953509.68, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953510.375, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953511.1, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953511.731, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953512.343, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953512.958, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953513.67, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953514.473, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953515.216, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953515.909, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953516.566, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953517.284, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953517.909, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953518.543, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953519.165, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953519.869, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953520.557, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953521.277, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953522.095, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953522.728, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953523.471, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953524.222, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953524.923, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953525.675, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953526.393, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953527.016, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953527.635, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953528.315, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953529.027, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953529.72, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953530.363, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953530.989, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953531.706, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953532.408, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953533.027, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953533.722, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953534.45, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953535.185, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953536.292, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953537.63, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953538.222, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953538.923, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953539.562, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953540.166, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953540.926, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953541.671, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953542.371, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953543.042, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953543.725, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953544.349, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953544.967, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953545.623, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953546.29, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953546.952, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953547.566, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953548.371, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953548.954, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953549.688, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953550.313, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953550.98, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953551.654, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953552.266, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953552.979, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953553.605, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953554.572, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953555.317, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953555.939, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953556.656, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953557.359, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953558.047, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953558.785, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953559.595, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953560.274, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953561.101, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953561.742, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953562.37, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953563.177, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953563.785, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953564.396, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953565.096, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953565.841, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953566.496, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

{"ts": 1786953567.145, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: POST https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/search \"HTTP/1.1 200 OK\""}

  [khub] scored 153/153
[khub] scored 153 questions in 113s

## Step 10 — Results: ours (no-reranker) vs. ours (cross-encoder) vs. khub

In [13]:
print("=" * 100)
print("DOC-LEVEL COMPARISON -- ours (no-reranker) vs. ours (cross-encoder) vs. khub")
print(f"{len(questions)} identical questions, {len(docs_info)} documents, "
      f"non-LLM exact-document-id matching on all three sides")
print("=" * 100)

three_way_rows = []
for k in K_VALUES:
    three_way_rows.append({
        "k": k,
        "recall@k -- ours (no-reranker)": round(recall_at_k(results_by_config["no-reranker"]["doc_ranks"], k), 4),
        "recall@k -- ours (cross-encoder)": round(recall_at_k(results_by_config["cross-encoder"]["doc_ranks"], k), 4),
        "recall@k -- khub": round(recall_at_k(khub_doc_ranks, k), 4),
    })
three_way_df = pd.DataFrame(three_way_rows)
print(three_way_df.to_string(index=False))

print(f"\nMRR@10 -- ours (no-reranker):    {mrr_at_10(results_by_config['no-reranker']['doc_ranks']):.4f}")
print(f"MRR@10 -- ours (cross-encoder):  {mrr_at_10(results_by_config['cross-encoder']['doc_ranks']):.4f}")
print(f"MRR@10 -- khub:                  {mrr_at_10(khub_doc_ranks):.4f}")

khub_docs_final = khub.get("/api/v1/documents").json()["documents"]
print(f"\nkhub library note: {len(SAMPLE_PDFS)} files uploaded this run (doc_type={KHUB_DOC_TYPE!r}) "
      f"are PERMANENT -- this account has no doc.delete capability. khub's library is now "
      f"{len(khub_docs_final)} documents (was {len(khub_docs_before)} before this run) -- "
      f"confirmed and accepted before running this section, not a silent side effect.")
khub.close()

====================================================================================================
DOC-LEVEL COMPARISON -- ours (no-reranker) vs. ours (cross-encoder) vs. khub
153 identical questions, 6 documents, non-LLM exact-document-id matching on all three sides
====================================================================================================
 k  recall@k -- ours (no-reranker)  recall@k -- ours (cross-encoder)  recall@k -- khub
 1                          0.8301                            0.9020            0.8693
 3                          1.0000                            0.9935            0.9869
 5                          1.0000                            1.0000            0.9935
10                          1.0000                            1.0000            1.0000

MRR@10 -- ours (no-reranker):    0.9129
MRR@10 -- ours (cross-encoder):  0.9479
MRR@10 -- khub:                  0.9282

{"ts": 1786953569.916, "level": "INFO", "logger": "httpx", "msg": "HTTP Request: GET https://khub.blackmushroom-f5c26536.eastus2.azurecontainerapps.io/api/v1/documents \"HTTP/1.1 200 OK\""}

khub library note: 6 files uploaded this run (doc_type='sample_pdfs_recall_eval') are PERMANENT -- this account has no doc.delete capability. khub's library is now 53 documents (was 48 before this run) -- confirmed and accepted before running this section, not a silent side effect.

## Step 11 — RAGAS: judged answer quality, ours vs. khub

Everything measured so far (Steps 5-10) is non-LLM retrieval scoring — it never checks
whether the *generated answer* is actually good. This section uses
[RAGAS](https://docs.ragas.io) — a real, independent evaluation library, not a
notebook reimplementation of it — to synthesize a fresh question set and judge both
systems' answers to it.

**Model assignment (deliberately separated):**
- **`gpt-5-nano` generates** — both RAGAS's own `TestsetGenerator` (the questions +
  reference answers below) and our system's own answers (`app.retrieval.rag.query.answer_query`,
  same as `container.settings.chat_model`'s default).
- **`claude-sonnet-5` only judges** (Step 13's `evaluate()` call) — never used to
  generate anything in this section, so it never grades its own or a same-model
  sibling's output.

**On "testing the images":** RAGAS's `TestsetGenerator` has **no native image/multimodal
generation support** — confirmed live (an open, unimplemented GitHub issue,
`explodinggradients/ragas` #2002). RAGAS only has multimodal *evaluation* metrics for
pre-built datasets that already contain image references, nothing that ingests raw
images to synthesize questions. In this system, that gap doesn't cost us anything real:
images and scanned pages are already transcribed to plain text by the vision model **at
ingestion time** (this pipeline's whole design — see `docs/ARCHITECTURE.md`), so an
image-derived chunk is just text by the time it exists at all. "Testing the images"
here concretely means: the whole-document text fed to `TestsetGenerator` below includes
every vision-transcribed chunk inline, in its original position — RAGAS's synthesizers
can draw questions from that content exactly like any other text (3 of 6 documents —
`3.pdf`, `4.pdf`, `6.pdf` — are fully scanned, so a real share of the fed text is
vision-transcribed). RAGAS just has no way to specifically *target* image-origin
passages, since it has no concept of modality — that limitation is real, not hidden.

This is a **separate, independently-synthesized** question set from the 153 used in the
non-LLM benchmark (different mechanism — RAGAS's knowledge-graph synthesis vs.
one-question-per-chunk) — a judged-answer-quality spot-check that complements the
retrieval-only benchmark above, not a replacement for it.

In [ ]:
from langchain_core.documents import Document
from langchain_openai import ChatOpenAI
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.llms import LangchainLLMWrapper
from ragas.run_config import RunConfig
from ragas.testset import TestsetGenerator


class _OurEmbeddingsLangchain:
    """Adapts our active embedder (bge-large-en-v1.5 this run) to the langchain
    Embeddings interface RAGAS expects."""
    def embed_documents(self, texts):
        return embedder.embed(list(texts))

    def embed_query(self, text):
        return embedder.embed([text])[0]


# Whole-document text, reassembled from already-ingested chunks in ordinal order --
# reuses the vision-OCR/parse work already paid for during Step 1's ingestion, no
# re-extraction. Capped per fed "document" (MAX_DOC_CHARS) rather than fed as one
# whole file: this gateway rate-limits gpt-5-nano to 10,000 tokens/60s window (measured
# live), and a single extractor call over an uncapped whole document (e.g. 2.pdf
# reassembles to ~49k chars, ~12k+ tokens) can itself need MORE tokens than an entire
# window allows -- that call then 429s on every retry forever, since it can never fit
# in one window no matter how long it waits. Splitting on our own existing chunk
# boundaries (never mid-sentence) keeps every fed sub-document safely within budget;
# multiple sub-documents sharing one `filename` in metadata is a normal, supported
# RAGAS pattern (a knowledge graph is built from many small documents regardless).
MAX_DOC_CHARS = 8000

ragas_docs = []
for d in docs_info:
    ordered = sorted(d["chunks"], key=lambda c: c.ordinal)
    buf, buf_len, n_sub = [], 0, 0
    for ch in ordered:
        if buf and buf_len + len(ch.text) > MAX_DOC_CHARS:
            ragas_docs.append(Document(page_content="\n\n".join(buf),
                                       metadata={"filename": d["doc"].filename}))
            n_sub += 1
            buf, buf_len = [], 0
        buf.append(ch.text)
        buf_len += len(ch.text)
    if buf:
        ragas_docs.append(Document(page_content="\n\n".join(buf),
                                   metadata={"filename": d["doc"].filename}))
        n_sub += 1
    print(f"  {d['doc'].filename}: {len(ordered)} chunks -> {n_sub} sub-document(s)")

print(f"\n{len(ragas_docs)} total documents fed to TestsetGenerator "
      f"(from {len(docs_info)} source files, capped at {MAX_DOC_CHARS:,} chars each)")

GENERATION_MODEL = "gpt-5-nano"   # generation only, never the judge (see Step 11 intro)
generator_llm = LangchainLLMWrapper(ChatOpenAI(
    model=GENERATION_MODEL, api_key=container.settings.litellm_api_key,
    base_url=container.settings.litellm_base_url.rstrip("/") + "/v1", temperature=0,
    max_retries=0,   # disable the OpenAI SDK's own sub-second retry-on-429 -- it fires
                     # independently of (and much faster than) RAGAS's own RunConfig
                     # backoff, so RAGAS's patient retry never got a real chance to
                     # wait out the rate-limit window (measured live during debugging).
))
generator_embeddings = LangchainEmbeddingsWrapper(_OurEmbeddingsLangchain())

generator = TestsetGenerator(llm=generator_llm, embedding_model=generator_embeddings)

# Sequential + a wait long enough to span the gateway's ~60s rate-limit window
# (measured live: gpt-5-nano is capped at 10 requests / 10,000 tokens per window).
generation_run_config = RunConfig(timeout=300, max_retries=5, max_wait=90, max_workers=1)

print(f"\nSynthesizing 30 questions + reference answers with RAGAS's own "
      f"TestsetGenerator (generation model={GENERATION_MODEL})... "
      f"this builds a knowledge graph over the {len(ragas_docs)} documents first "
      f"(the expensive part), then synthesizes scenarios -- real RAGAS machinery, "
      f"not a notebook substitute. This will take a while (rate-limit-safe pacing).")

ragas_testset = generator.generate_with_langchain_docs(
    ragas_docs, testset_size=30, run_config=generation_run_config)
ragas_df = ragas_testset.to_pandas()

print(f"\nRAGAS synthesized {len(ragas_df)} question/reference-answer pairs.")
print("synthesizer_name distribution:")
print(ragas_df["synthesizer_name"].value_counts().to_string())

## Step 12 — Answering all synthesized questions with both systems

**Ours** goes through the real, unmodified production path,
`app.retrieval.rag.query.answer_query` — deliberately *not* the `is_query=True` retrieval-only
bypass the non-LLM benchmarks used; RAGAS should measure the system exactly as a real
caller experiences it. **khub** goes through its real answer-generation endpoint,
`POST /api/v1/ask` (a different endpoint from `/api/v1/search` used earlier — same
already-granted account, no new permission needed), scoped to our uploaded 6 files via
the same `doc_type` tag as before, at khub's own natural `top_k` default (6) rather than
forced to match ours.

In [ ]:
import httpx
from app.retrieval.rag.query import answer_query

# Fresh khub session (the earlier client was closed at the end of Step 10; the
# session cookie may also have expired by now) -- same login flow as Step 8.
khub = httpx.Client(base_url=KHUB_BASE_URL, timeout=120.0)
khub.post("/api/v1/auth/login",
          json={"email": KHUB_LOGIN_EMAIL, "password": KHUB_LOGIN_PASSWORD}).raise_for_status()
print("khub: re-authenticated for /api/v1/ask")


def khub_ask(client, question, doc_type, top_k=6, max_attempts=4):
    last_exc = None
    for attempt in range(1, max_attempts + 1):
        try:
            r = client.post("/api/v1/ask", json={
                "question": question, "top_k": top_k, "filters": {"doc_type": doc_type},
            })
            r.raise_for_status()
            body = r.json()
            contexts = [p.get("snippet") or "" for p in body.get("passages", [])]
            return body.get("answer", ""), contexts
        except httpx.HTTPStatusError as exc:
            last_exc = exc
            if exc.response.status_code < 500 or attempt == max_attempts:
                raise
            time.sleep(5 * attempt)
    raise last_exc


ours_samples, khub_samples = [], []
t0 = time.perf_counter()
for i, row in ragas_df.iterrows():
    question = row["user_input"]
    reference = row["reference"]
    reference_contexts = list(row["reference_contexts"])

    ours_result = answer_query(container, tenant_id, question, top_k=5)
    ours_samples.append({
        "user_input": question, "retrieved_contexts": ours_result.contexts,
        "response": ours_result.answer, "reference": reference,
        "reference_contexts": reference_contexts,
    })

    khub_answer, khub_contexts = khub_ask(khub, question, KHUB_DOC_TYPE)
    khub_samples.append({
        "user_input": question, "retrieved_contexts": khub_contexts or [""],
        "response": khub_answer, "reference": reference,
        "reference_contexts": reference_contexts,
    })
    print(f"  [{i + 1}/{len(ragas_df)}] {question[:70]}")

print(f"\nanswered {len(ragas_df)} questions with both systems in "
      f"{time.perf_counter() - t0:.0f}s")

## Step 13 — RAGAS scoring: one independent judge, both systems

`claude-sonnet-5` judges both result sets — it generated nothing in this section (Step
11's testset and Step 12's `ours_samples` both used `gpt-5-nano`; khub uses whatever it
uses internally), so it isn't grading its own or a sibling model's output. Full metric
suite: 5 LLM-judged + 2 non-LLM (string-distance) metrics, identical set and config
already used in `eval/run_ragas.py` / `notebooks/khub_vs_pipeline_comparison.ipynb`.

In [ ]:
from ragas import EvaluationDataset, RunConfig, evaluate
from ragas.metrics import (
    AnswerCorrectness,
    Faithfulness,
    LLMContextPrecisionWithReference,
    LLMContextRecall,
    NonLLMContextPrecisionWithReference,
    NonLLMContextRecall,
    ResponseRelevancy,
)

JUDGE_MODEL = "claude-sonnet-5"   # judge only -- never used for generation above
judge_llm = LangchainLLMWrapper(ChatOpenAI(
    model=JUDGE_MODEL, api_key=container.settings.litellm_api_key,
    base_url=container.settings.litellm_base_url.rstrip("/") + "/v1", temperature=0,
    max_retries=0,   # same rate-limit lesson as Step 11's generator_llm: disable the
                     # OpenAI SDK's own fast sub-second retry so RAGAS's own patient
                     # RunConfig backoff (below) is the only retry layer in control.
))
judge_embeddings = LangchainEmbeddingsWrapper(_OurEmbeddingsLangchain())

ragas_metrics = [
    Faithfulness(),
    ResponseRelevancy(),
    LLMContextPrecisionWithReference(),
    LLMContextRecall(),
    AnswerCorrectness(),
    NonLLMContextPrecisionWithReference(),
    NonLLMContextRecall(),
]
# Sequential + a wait long enough to span the gateway's rate-limit window (same
# measured constraint as Step 11 -- this judge model may share limits too).
run_cfg = RunConfig(timeout=300, max_retries=5, max_wait=90, max_workers=1)

print(f"judge: {JUDGE_MODEL} | metrics: {[m.name for m in ragas_metrics]}\n")

print(f"scoring OURS ({len(ours_samples)} samples)... (rate-limit-safe pacing, will take a while)")
ours_dataset = EvaluationDataset.from_list(ours_samples)
ours_result = evaluate(dataset=ours_dataset, metrics=ragas_metrics,
                       llm=judge_llm, embeddings=judge_embeddings, run_config=run_cfg)
ours_ragas_df = ours_result.to_pandas()
ours_ragas_df.to_csv("eval/khub_compare_sample_pdfs_ours.csv", index=False)
print(ours_result)

print(f"\nscoring KHUB ({len(khub_samples)} samples)...")
khub_dataset = EvaluationDataset.from_list(khub_samples)
khub_result = evaluate(dataset=khub_dataset, metrics=ragas_metrics,
                       llm=judge_llm, embeddings=judge_embeddings, run_config=run_cfg)
khub_ragas_df = khub_result.to_pandas()
khub_ragas_df.to_csv("eval/khub_compare_sample_pdfs_khub.csv", index=False)
print(khub_result)

## Step 14 — Side-by-side: ours vs. khub, RAGAS-judged

In [ ]:
def _metric_means(df):
    return df.select_dtypes(include="number").mean()

ours_means = _metric_means(ours_ragas_df)
khub_means = _metric_means(khub_ragas_df)

ragas_comparison = pd.DataFrame({"ours": ours_means, "khub": khub_means})
ragas_comparison["delta (ours - khub)"] = ragas_comparison["ours"] - ragas_comparison["khub"]
ragas_comparison = ragas_comparison.round(4)
print(ragas_comparison.to_string())
ragas_comparison.to_csv("eval/khub_compare_sample_pdfs_summary.csv")
print("\nsaved -> eval/khub_compare_sample_pdfs_summary.csv")

print("\nHonest read (no automatic winner declared):")
NOTABLE = 0.05
for metric, row in ragas_comparison.iterrows():
    delta = row["delta (ours - khub)"]
    if abs(delta) < NOTABLE:
        verdict = "roughly tied"
    elif delta > 0:
        verdict = f"ours ahead by {delta:.3f}"
    else:
        verdict = f"khub ahead by {abs(delta):.3f}"
    print(f"{metric:35} ours={row['ours']:.3f}  khub={row['khub']:.3f}  -> {verdict}")

print(
    "\nCaveats:\n"
    "- khub's retrieved_contexts come from its `snippet` field, which may be a "
    "truncated view of its underlying passage -- can understate its context-precision/"
    "recall relative to faithfulness/correctness.\n"
    "- Reference answers are RAGAS-synthesized (from gpt-5-nano reading whole-document "
    "text), not human-written -- standard practice for this tool, still a synthetic "
    "gold label.\n"
    "- This is a 30-question spot-check on judged answer quality, separate from the "
    "153-question non-LLM retrieval benchmark above -- the two should not be conflated."
)
khub.close()